Move to IBM copyright headers
Terracotta-OSS/bigmemory-core-storage pull request #2
Opened 2024-07-23 09:34 UTC by guptakshit

All files except Jenkinsfile are Terracotta Public License

2024-07-23 09:36 UTC, guptakshit commented on pom.xml
> +      <organization>Super iPaaS Integration LLC, an IBM Company</organization>
I referred https://github.com/Terracotta-OSS/offheap-store/pull/83/commits/4e702534a149b6f39ecdaee585383d20c6e9c0f5

2024-07-23 21:15 UTC, chrisdennis requested changes
I'm going to say we should go ahead and make the TPL to Apache transition in this PR. Then let's leave it open pending the TPL decision later this week. Once made we can then just merge the one PR and be done.

2024-07-24 09:45 UTC, aurbroszniowski commented
> I'm going to say we should go ahead and make the TPL to Apache transition in this PR. Then let's leave it open pending the TPL decision later this week. Once made we can then just merge the one PR and be done.

If we need to wait for a decision for the TPL change, shouldn't we wait to make the changes in the code too? I'm asking because I have 2 other PRs with a fairly high number of TPL licenses so I'm wondering if I should already go ahead with changes to Apache, but if it's not sure, I don't want to make changes now and revert them later

2024-07-24 13:08 UTC, chrisdennis commented
> > I'm going to say we should go ahead and make the TPL to Apache transition in this PR. Then let's leave it open pending the TPL decision later this week. Once made we can then just merge the one PR and be done.
> 
> @chrisdennis If we need to wait for a decision for the TPL change, shouldn't we wait to make the changes in the code too? I'm asking because I have 2 other PRs with a fairly high number of TPL licenses so I'm wondering if I should already go ahead with changes to Apache, but if it's not sure, I don't want to make changes now and revert them later

@aurbroszniowski we can wait sure... hopefully should know by end of Thursday at the latest.

2024-07-26 13:32 UTC, guptakshit commented
does svn link https://github.com/Terracotta-OSS/bigmemory-core-storage/blob/1fc49360098658b75ed4b3457de774b39d8888db/Jenkinsfile#L18 needs to be replaced?

2024-07-30 10:23 UTC, mathieucarbou approved these changes

2024-07-30 10:24 UTC, merged